/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import static javassist.CtMethod.ConstParameter.string;
import javax.swing.ImageIcon;

/**
 *
 * @author Kur013
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public FrmMenu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Img/CarSoft-removebg-preview.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        //jLabel5.setForeground(Color.WHITE);
        //jFrame.setForeground(Color.CYAN);
        //btnVehículos.setBackground(Color.green);
        //btnEmpleados.setBackground(Color.green);
        //btnClientes.setBackground(Color.green);
        //btnPedidos.setBackground(Color.green);
        //btnVentas.setBackground(Color.green);
        //btnCerrar.setBackground(Color.green);
        //btnBancos.setBackground(Color.green);
        //btnPiezas.setBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBancos = new javax.swing.JButton();
        btnPiezas = new javax.swing.JButton();
        btnVehículos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBienvenido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lIDEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cliente.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(80, 260, 213, 109);

        btnVentas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ventas.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas);
        btnVentas.setBounds(80, 534, 213, 109);

        btnEmpleados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Empleado.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleados);
        btnEmpleados.setBounds(80, 398, 213, 109);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CarSoft-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(589, 0, 200, 195);

        btnBancos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBancos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Banco.png"))); // NOI18N
        btnBancos.setText("Bancos");
        btnBancos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancosActionPerformed(evt);
            }
        });
        getContentPane().add(btnBancos);
        btnBancos.setBounds(323, 260, 213, 109);

        btnPiezas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Pieza.png"))); // NOI18N
        btnPiezas.setText("Piezas");
        btnPiezas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiezasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPiezas);
        btnPiezas.setBounds(576, 398, 213, 109);

        btnVehículos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVehículos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Vehiculo.png"))); // NOI18N
        btnVehículos.setText("Vehículos");
        btnVehículos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehículos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehículosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehículos);
        btnVehículos.setBounds(576, 260, 213, 109);

        btnPedidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Pedidos.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedidos);
        btnPedidos.setBounds(323, 398, 213, 109);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1440, 486, 0, 278);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Visión");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1031, 340, 72, 29);

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cerrar sesion.png"))); // NOI18N
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(576, 534, 213, 109);

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(1270, 10, 93, 41);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("en la comercialización de piezas ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(980, 410, 190, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ser una empresa especializada");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(980, 390, 190, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("y vehículos nuevos. Contar con ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(980, 430, 180, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("tecnología de punta que");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(980, 470, 180, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("garantice siempre un servicio");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(980, 490, 180, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("integral de máxima calidad.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(980, 510, 180, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("personal altamente calificado y");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(980, 450, 180, 20);

        txtBienvenido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtBienvenido);
        txtBienvenido.setBounds(80, 50, 450, 35);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1958, 1080);

        lIDEmpleado.setText("0");
        getContentPane().add(lIDEmpleado);
        lIDEmpleado.setBounds(170, 120, 6, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        Ventas v = new Ventas();
        v.setCmbEmpleado(Integer.parseInt(lIDEmpleado.getText()));
        v.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        IniciodeSesion m = new IniciodeSesion();
        m.setVisible(true);
        //FrmMenu me = new FrmMenu();
        //me.setVisible(false);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        FrmCliente m = new FrmCliente();
        m.setVisible(true);
        FrmMenu me = new FrmMenu();
        me.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiezasActionPerformed
        FrmPieza m = new FrmPieza();
        m.setVisible(true);
        FrmMenu me = new FrmMenu();
        me.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnPiezasActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        FrmEmpleados m = new FrmEmpleados();
        m.setVisible(true);
        FrmMenu me = new FrmMenu();
        me.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnVehículosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehículosActionPerformed
        FrmVehiculos v= new FrmVehiculos();
        v.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehículosActionPerformed

    private void btnBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancosActionPerformed
        FrmBanco b = new FrmBanco();
        b.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBancosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        FrmPedidos p = new FrmPedidos();
        p.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBancos;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPiezas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVehículos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lIDEmpleado;
    public static javax.swing.JLabel txtBienvenido;
    // End of variables declaration//GEN-END:variables
}
