/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;
import Clases.Empleado;
import Clases.Hash;
import Clases.Persona;
import Clases.Usuarios;
import JPAController.EmpleadoJpaController;
import JPAController.PersonaJpaController;
import JPAController.UsuariosJpaController;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Kur013
 */
public class IniciodeSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciodeSesion
     */
    
    private Component confirm;
      UsuariosJpaController  usuarioDao = new UsuariosJpaController();
      PersonaJpaController personaDao= new PersonaJpaController();
      EmpleadoJpaController empleadoDao = new EmpleadoJpaController();
      private String user, password;
      
    public IniciodeSesion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Img/CarSoft-removebg-preview.png")).getImage());
         txt_usuario.setFocusable(true);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void datos(String us, String pas){
    user  = "jose.lopez1";
    password = "admin";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_password = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_password);
        btn_password.setBounds(700, 420, 130, 30);
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(700, 380, 130, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 390, 90, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 430, 90, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CarSoft-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(640, 10, 200, 190);

        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ingresar.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(680, 500, 135, 59);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Inicio de Sesión");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 320, 108, 17);

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(1250, 20, 93, 41);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, -30, 1750, 1130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_passwordActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        if (txt_usuario.getText().equals("") && btn_password.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Usuario y contraseña estan vacios\nIngrese su usuario y contraseña");
            txt_usuario.setFocusable(true);
            return;
       }
       else{
           
       }
       if (txt_usuario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Usuario esta vacio\nIngrese su usuario");
            txt_usuario.setFocusable(true);
            return;
       }
       else{
           
       }
       if (btn_password.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Contraseña esta vacio\nIngrese su contraseña");
            btn_password.setFocusable(true);
            return;
        }
       
       
       
        java.util.List<Usuarios> temp;
        temp = usuarioDao.findUsuariosEntities();
        boolean flag = false;
        boolean flag2 = false;
        boolean flag3 = false;
        for(Usuarios u : temp){
            if(u.getId_Nombre().equals(txt_usuario.getText())){
                flag=true;
                if(u.getContraseña().equals(Hash.getHash(btn_password.getText()))){
                    flag2=true;
                    if(u.isEstado()){
                        flag3=true;
                    }
                }
                
                
            }
        }
        if(flag && flag2 && flag3){
            FrmMenu menu = new FrmMenu();
            menu.setVisible(true);
            
            Empleado temp2 = new Empleado();
            Persona temp3 = new Persona();
            for(Usuarios u : temp){
                if(u.getId_Nombre().equals(txt_usuario.getText())){
                    temp2=empleadoDao.findEmpleado(u.getId_Empleado());
                    temp3=personaDao.findPersona(temp2.getId_Persona());
                
                }
            
            
            }
            
            
            
            FrmMenu.txtBienvenido.setText("Bienvenido "+temp3.getNombre()+" "+temp3.getApellido());
            FrmMenu.lIDEmpleado.setText(String.valueOf(temp2.getId_Empleado()));
            
            this.dispose();
        }
        else if (flag && !flag2){
             JOptionPane.showMessageDialog(this, "La contraseña no es valida\n Ingrese su contraseña","Contraseña Incorrecta",0);
            btn_password.setFocusable(true);
        }
        else if (flag && flag2 && !flag3){
            JOptionPane.showMessageDialog(this,"Cuenta inactiva, pongase en contacto con el Gerente o departamento de TI","Cuenta Inactiva",0);
        }
        else if(!flag){
            JOptionPane.showMessageDialog(this, "Usuario no encontrado en el sistema, Asegurese que su Usuario este escrito correctamente","Usuario Invalido",0);
        }
        /*       datos(user, password);
        if(user.equals(txt_usuario.getText()) && password.equals(btn_password.getText())){
            FrmMenu menu = new FrmMenu();
            menu.setVisible(true);
            this.dispose();
        }else if (txt_usuario.getText().equals("") && btn_password.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Usuario y contraseña estan vacios\nIngrese su usuario y contraseña");
            txt_usuario.setFocusable(true);
        }else if (txt_usuario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Usuario esta vacio\nIngrese su usuario");
            txt_usuario.setFocusable(true);
        }else if (btn_password.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Contraseña esta vacio\nIngrese su contraseña");
            btn_password.setFocusable(true);
        }else if(txt_usuario.getText().compareTo(user)!=0 && btn_password.getText().compareTo(password)!=0){
            JOptionPane.showMessageDialog(this, "El Usuario o la contraseña no son validos\n Ingrese su usuario y contraseña");
            txt_usuario.setFocusable(true);
        }else if(txt_usuario.getText().compareTo(user)!=0){
            JOptionPane.showMessageDialog(this, "Usuario no valido\n Ingrese su usuario nuevamente");
            txt_usuario.setFocusable(true);
        }else if(btn_password.getText().compareTo(password)!=0){
            JOptionPane.showMessageDialog(this,"Contraseña no valida\nIngrese su contraseña nuevamente");
            btn_password.setFocusable(true);
        }
    */
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciodeSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPasswordField btn_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
